numpy
- create array
- maths
- operations

In [1]:
x=[[1,2,3],
    [3,2,1]]
print(x)

[[1, 2, 3], [3, 2, 1]]


In [4]:
sums=0
for i in x:
    for j in i:
        sums+=j
print(sums)

12


Without numpy doing maths(matrix maths) is very complex in any language

In [1]:
import numpy as np

In [4]:
x=np.array([
    [1,2,3],
    [3,2,1]
])
print(x)
print(type(x))
print(x.shape)

[[1 2 3]
 [3 2 1]]
<class 'numpy.ndarray'>
(2, 3)


In [6]:
print(x.sum())
print(x.sum(axis=0)) #sum of each column
print(x.sum(axis=1)) #sum of ech row

12
[4 4 4]
[6 6]


In [9]:
a=np.array([1,2,3])
b=np.array([[1,2,4],[2,3,5]])
c=np.array([[[1,2],[2,3],[4,4]]])
print(a.shape,a.ndim)
print(b.shape,b.ndim)
print(c.shape,c.ndim)

(3,) 1
(2, 3) 2
(1, 3, 2) 3


#matrix creation
- sequntial 
    - arrange
    - linspace
- random
    - rand
    - randint
    - uniform

In [27]:
x= np.arange(1,10,2)    #start end step

print(x)

y=np.linspace(1,11,20)  # start end no. of points
y

[1 3 5 7 9]


array([ 1.        ,  1.52631579,  2.05263158,  2.57894737,  3.10526316,
        3.63157895,  4.15789474,  4.68421053,  5.21052632,  5.73684211,
        6.26315789,  6.78947368,  7.31578947,  7.84210526,  8.36842105,
        8.89473684,  9.42105263,  9.94736842, 10.47368421, 11.        ])

In [35]:
np.arange(1,31,1).reshape(3,2,5)

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]],

       [[21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]]])

In [38]:
x1=np.array([[1,2,3],[4,5,6]])
x2=np.array([[1,8,3],[9,5,6]])

In [42]:
print(x1)
print(x2)
print(x1+x2)
print(x2*x1)
print(x2-x1)
print(x2/x1)
print(x2**x1)
print(x2//x1)
print(x2%x1)
print(x2>x1)
print(x2<x1)
print(x2>=x1)
print(x2<=x1)


[[1 2 3]
 [4 5 6]]
[[1 8 3]
 [9 5 6]]
[[ 2 10  6]
 [13 10 12]]
[[ 1 16  9]
 [36 25 36]]
[[0 6 0]
 [5 0 0]]
[[1.   4.   1.  ]
 [2.25 1.   1.  ]]
[[    1    64    27]
 [ 6561  3125 46656]]
[[1 4 1]
 [2 1 1]]
[[0 0 0]
 [1 0 0]]
[[False  True False]
 [ True False False]]
[[False False False]
 [False False False]]
[[ True  True  True]
 [ True  True  True]]
[[ True False  True]
 [False  True  True]]


In [48]:
a=np.random.rand(3,3,2)
a

array([[[0.00539338, 0.01464449],
        [0.10460865, 0.21676615],
        [0.08388847, 0.31621932]],

       [[0.78573385, 0.41456606],
        [0.65105955, 0.35224125],
        [0.49587568, 0.9348485 ]],

       [[0.79470715, 0.61910473],
        [0.21130668, 0.46117281],
        [0.86500401, 0.14088562]]])

In [50]:
np.set_printoptions(precision=2)
a

array([[[0.01, 0.01],
        [0.1 , 0.22],
        [0.08, 0.32]],

       [[0.79, 0.41],
        [0.65, 0.35],
        [0.5 , 0.93]],

       [[0.79, 0.62],
        [0.21, 0.46],
        [0.87, 0.14]]])

In [54]:
b=np.random.randint(0,10,(3,3))
b

array([[0, 7, 3],
       [9, 7, 1],
       [9, 5, 6]])

In [58]:
c=np.random.uniform(0,10,(3,3))
c

array([[1.88, 8.75, 3.94],
       [1.19, 4.8 , 1.86],
       [2.63, 8.23, 0.58]])